spring:
    jpa:
        show_sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                storage_engine: innodb
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: false
    datasource:
        hikari:
            jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL